package dto;

import java.io.Serializable;

/*
DROP TABLE RESERVE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_RESERVE;

CREATE TABLE RESERVE(
	SEQ NUMBER(8) PRIMARY KEY,
	
	ID VARCHAR2(50) NOT NULL,
	HOTELNAME VARCHAR2(50) NOT NULL,
	REQUEST VARCHAR2(200),
	REALDATE VARCHAR2(50) NOT NULL,
	
	REGDATE DATE NOT NULL,
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_RESERVE
START WITH 1
INCREMENT BY 1;

ALTER TABLE RESERVE
ADD CONSTRAINT FK_RESERVE_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

ALTER TABLE RESERVE
ADD CONSTRAINT FK_RESERVE_HOTELNAME FOREIGN KEY(HOTELNAME)
REFERENCES HOTEL(HOTELNAME);
*/


public class ReserveDto implements Serializable {

}
