package dto;

import java.io.Serializable;

/*
DROP TABLE REVIEW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW(
	NUM NUMBER(8) NOT NULL,
	
	TITLE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(300) NOT NULL,
	
	SCORE NUMBER(10) NOT NULL,
	
	READCOUNT NUMBER(8) NOT NULL,
	DEL NUMBER(1) NOT NULL,
	REGDATE DATE NOT NULL
);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_NUM FOREIGN KEY(NUM)
REFERENCES RESERVE(ID);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_HOTELNAME FOREIGN KEY(HOTELNAME)
REFERENCES HOTEL(HOTELNAME);
*/

public class ReviewDto implements Serializable {

}
